### ISSUE TITLE
Unsubscribe/Subscribe to stream

### ISSUE THREAD

**Issue by dima-dmytruk23** [LUCIT-Systems-and-Development/unicorn-binance-websocket-api#315]
### Version of this library.

1.42.0

### Solution to Issue cannot be found in the documentation or other Issues and also occurs in the latest version of this library.

- [X] I checked the documentation and other Issues. I am using the latest version of this library.

### Hardware?

Local server/workstation

### Operating System?

Linux

### Python version?

Python3.7

### Installed packages

```shell
unicorn-binance-websocket-api 1.42.0
unicorn-fy                    0.12.2
websockets                    10.4
```

### Logging output

https://gist.github.com/dima-dmytruk23/0e7500d94292a3889e3eecfa769385f8

### Processing method?

stream_buffer

### Used endpoint?

concerns all

### Issue

I initially have a stream that is subscribed to futures (at the time of launch, this is an empty list). This list is filled/changed by messages from the message broker. I was thinking of doing this with

```python
self.manager.unsubscribe_from_stream(stream_id=self.stream_id, markets=old_symbols)
self.manager.subscribe_to_stream(stream_id=self.stream_id, markets=new_symbols)
```

But for some reason after that - I do not receive data from the Binance. As far as I can see, this only happens _if I initially have an empty list of tickers_.

**Comment by oliver-zehentleitner** [comment]
https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/blob/ba0bbfd3cce0f193f2b3258dff3bc2a79f92d13f/unicorn_binance_websocket_api/manager.py#L1458

We build the URI for a "raw stream": https://binance-docs.github.io/apidocs/spot/en/#websocket-market-streams

If you want to update this a PR is welcome.

**Comment by dima-dmytruk23** [comment]
> https://github.com/LUCIT-Systems-and-Development/unicorn-binance-websocket-api/blob/ba0bbfd3cce0f193f2b3258dff3bc2a79f92d13f/unicorn_binance_websocket_api/manager.py#L1458
> 
> We build the URI for a "raw stream": https://binance-docs.github.io/apidocs/spot/en/#websocket-market-streams
> 
> If you want to update this a PR is welcome.

Any idea how to handle this correctly? Use a combined stream? Do not create a stream if there are no tickers?

**Comment by oliver-zehentleitner** [comment]
In itself, it is not intended that ubwa can create an empty stream. I also think that `create_stream()` returns `False` in your case. (I hope I'm not wrong now, but that's what I would expect ^^) Which would actually implement it "correctly".

If you want to use the full potential of the Binance API and create a combined stream instead of raw, then check if an empty stream is allowed. for that method i'm not sure... 

I personally would be reluctant to attack this because it is now copatible with all APIs even binancechain. It's a lot of work and needs a lot of testing and the surplus is minimal.
